### ISSUE TITLE
1. Configurar Vite y estructura base

### ISSUE THREAD

**Issue by EduMMorenolp** [EduMMorenolp/La-Guia-del-Programador#10]
Descripción:
Configurar el entorno de desarrollo para el frontend usando Vite como bundler. Este paso incluye crear la estructura base del proyecto y asegurarse de que todo esté funcionando correctamente.

Tareas:

Instalar Vite y configurarlo para React.
Crear la estructura de carpetas: assets, components, pages, styles, main.js.
Verificar que la aplicación de React se inicie correctamente en el navegador.

**Comment by ILMPI** [comment]
To read:
https://vite.dev/guide/
https://www.simform.com/blog/principles-of-scalable-front-ends/
https://dev.to/alisamir/building-a-clean-and-scalable-frontend-architecture-1icc?signin=true
