### ISSUE TITLE
Implementar protección contra IDOR

### ISSUE THREAD

**Issue by LautaroColella** [EduMMorenolp/La-Guia-del-Programador#84]
### **Descripción del problema:**
Actualmente la lógica del backend no verifica que un usuario tenga ownership sobre un recurso, solo verifica que el usuario que intenta acceder al recurso esté autorizado. Es decir, si un usuario no autenticado intenta acceder a los favoritos del usuario pepito, no puede. Pero si un usuario autenticado jorgito intenta acceder a los favoritos de pepito, si puede. Enumerar los posibles recursos donde suceda este problema y aplicar la misma lógica.
Esta vulnerabilidad se llama [Insecure Direct Object Reference](https://en.wikipedia.org/wiki/Insecure_direct_object_reference)

Posible fix:
- Verificar que el identificador del usuario que intenta acceder al recurso (en este caso, los favoritos) coincida con el identificador de ownership del recurso en la base de datos.

**Comment by LautaroColella** [comment]
**No cerrar este issue hasta enumerar los posibles recursos que sean vulnerables a IDOR.**

Fixee el IDOR para los favoritos de los usuarios de la siguiente manera:
El router usa el handler `authenticateToken`:

`router.get(
  '/:userId/favorites',
  authenticateToken,
  usersController.getUserFavorites
);`

Lo que significa que ahora la request que se pasa al controller `usersController` contiene un objeto `user` con el identificador del usuario autenticado. Dicho identificador proviene del JWT por lo que se obtiene una autenticación fiable. Este identificador NO es el mismo que el de `req.params` que viene de `/:userId/favorites`. El identificador de `req.params` es un input de usuario, por lo que NO es fiable como método de autenticación.
Para verificar que un usuario autenticado pueda acceder a sus favoritos, ambos identificadores deben coincidir, tanto el que proviene del JWT, como el del `req.params`. De esta manera se demuestra que el usuario que intenta ver los favoritos tiene la autorización correspondiente.
Entonces, en el controller:
```
const { userId } = req.params;
const { userIdFromJwt } = req.user;
if (userId !== userIdFromJwt) {
  throw {
    statusCode: 403,
    message: "No puedes ver los favoritos de otro usuario",
  };
}
```

**Comment by EduMMorenolp** [comment]
Solución implementada: Se corrigió la vulnerabilidad añadiendo una validación adicional en el controlador de la ruta de favoritos. Ahora, además de la autenticación mediante el JWT (que proporciona un identificador confiable del usuario), se verifica que el identificador del usuario en la solicitud (req.params.userId) coincida con el identificador del usuario autenticado (req.user.userId). Esto asegura que solo el usuario autenticado puede acceder a sus propios recursos, como sus favoritos.

Código corregido:

```bash
const { userId } = req.params;
const { userIdFromJwt } = req.user;

if (userId !== userIdFromJwt) {
  throw {
    statusCode: 403,
    message: "No puedes ver los favoritos de otro usuario",
  };
}
```

Con esta mejora, aseguramos que un usuario no pueda acceder a los recursos de otro usuario, resolviendo la vulnerabilidad de IDOR.
